### PR TITLE
refactor: create module structure

### PR DESCRIPTION
**Pull request by Mohammer5**
- [x] Rename components to modules
- [x] Move components into their folders
- [ ] ~~Move files in utils folders~~

### CODE REVIEW

**Comment by Mohammer5** [comment]
@Birkbjo @HendrikThePendric Any idea what to do with the files in the utils folder? I could move them into the Navigation module as well, but it wouldn't be obvious to me to look there if I wasn't familiar with the codebase

**Comment by HendrikThePendric** [comment]
I don't mind leaving the `utils` folder as it is.
About `constants`: these seems to contain mainly configuration, perhaps `config` would be a better name?
About `modules`: this seems to be full of components, so why don't we just name it `components`? Are different things getting added later?

**Comment by Mohammer5** [comment]
> I don't mind leaving the utils folder as it is.

:+1: 

> About constants: these seems to contain mainly configuration, perhaps config would be a better name?

:+1: 

> About modules: this seems to be full of components, so why don't we just name it components? Are different things getting added later?

I think we'll have all kind of stuff in here, it's just components now because the app currently doesn't do anything but displaying stuff

**Comment by HendrikThePendric** [comment]
> I think we'll have all kind of stuff in here, it's just components now because the app currently doesn't do anything but displaying stuff

👍

**Comment by Mohammer5** [comment]
@HendrikThePendric I've renamed the constants folder. I think this should be ready to be merged if neither you nor @Birkbjo have any objections

**Pull request merged**
